%%writefile app.py
import streamlit as st
import json
import pandas as pd
from datetime import datetime

# Page Configuration
st.set_page_config(page_title="Medical EMR Dashboard", page_icon="🏥", layout="wide")

# Custom CSS for Medical Look
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; border: 1px solid #e1e4e8; }
    .report-header { border-bottom: 3px solid #2e5a88; padding-bottom: 10px; margin-bottom: 20px; }
    </style>
    """, unsafe_allow_html=True)

def parse_fhir_bundle(bundle):
    patient_info = {"Name": "N/A", "Age/Sex": "N/A", "Gender": "N/A"}
    practitioner = "N/A"
    observations = []

    for entry in bundle.get('entry', []):
        res = entry.get('resource', {})
        res_type = res.get('resourceType')

        if res_type == 'Patient':
            name = res.get('name', [{}])[0]
            patient_info["Name"] = name.get('text') or f"{name.get('given', [''])[0]} {name.get('family', '')}"
            patient_info["Gender"] = res.get('gender', 'N/A').title()
            # Try to get age from extension or birthDate
            patient_info["Age/Sex"] = res.get('birthDate') or "N/A"

        elif res_type == 'Practitioner':
            practitioner = res.get('name', [{}])[0].get('text', 'N/A')

        elif res_type == 'Observation':
            test = res.get('code', {}).get('coding', [{}])[0].get('display', 'Unknown')
            code = res.get('code', {}).get('coding', [{}])[0].get('code', 'N/A')
            
            # Extract Value and Unit
            val_qty = res.get('valueQuantity', {})
            val_str = res.get('valueString', '')
            val = val_qty.get('value', val_str)
            unit = val_qty.get('unit', '')
            
            observations.append({
                "Test Name": test,
                "LOINC Code": code,
                "Result": f"{val} {unit}"
            })

    return patient_info, practitioner, observations

# --- UI START ---
st.title("🏥 AI-Driven EMR Extraction System")
st.markdown("### Stage 8: Semantic Clinical Validation Dashboard")
st.write("---")

# File uploader
uploaded_file = st.sidebar.file_name = "Upload FHIR JSON"
uploaded_file = st.sidebar.file_uploader("Choose a FHIR JSON file", type="json")

if uploaded_file is not None:
    data = json.load(uploaded_file)
    p_info, doc, obs_list = parse_fhir_bundle(data)

    # 1. Patient Profile Header
    st.markdown(f"<div class='report-header'><h2>Patient Report: {p_info['Name']}</h2></div>", unsafe_allow_html=True)
    
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("Patient Name", p_info["Name"])
    with col2:
        st.metric("Gender", p_info["Gender"])
    with col3:
        st.metric("Ordering Doctor", doc)
    with col4:
        st.metric("Report Date", datetime.now().strftime("%d-%m-%Y"))

    # 2. Lab Results Table
    st.subheader("Laboratory Findings")
    if obs_list:
        df = pd.DataFrame(obs_list)
        st.table(df)
    else:
        st.warning("No clinical observations found in this record.")

    # 3. Raw Data Inspection (For Developers)
    with st.expander("View Raw FHIR JSON"):
        st.json(data)
    
    # 4. Download Option
    st.sidebar.markdown("---")
    st.sidebar.download_button(
        label="Download Validated FHIR JSON",
        data=json.dumps(data, indent=2),
        file_name="validated_emr.json",
        mime="application/json"
    )

else:
    st.info("Please upload the `final_record.json` generated by your OCR pipeline to see the dashboard.")
    # Show a sample empty state
    st.image("https://img.freepik.com/free-vector/medical-technology-science-background_53876-117812.jpg", use_column_width=True)